export const DIRECTION = 'DIRECTION';
export const PATHNAME = 'PATHNAME';
export const MINIMENU = 'MINIMENU';
export const TOLOGIN = 'TOLOGIN';
export const TEST = 'TEST';
export const ADDCHANNEL = 'ADDCHANNEL';
export const GETCHANNELs = 'GETCHANNELs';
export const GETWXMENU = 'GETWXMENU';
export const ADDWXMENU = 'ADDWXMENU';
export const MAKEMENU = 'MAKEMENU';
export const GETUSERS = 'GETUSERS';
export const DELETEWXMENU = 'DELETEWXMENU';
export const EDITWXMENU = 'EDITWXMENU';
export const SAVETHISMESSAGE = 'SAVETHISMESSAGE';
export const GETWXMESSAGES = 'GETWXMESSAGES';
export const CHECKOUTUSER = 'CHECKOUTUSER';
export const TOSENDMESSAGETOSOMEONE = 'TOSENDMESSAGETOSOMEONE';
export const UPLOADIMAGE = 'UPLOADIMAGE';
export const DELETETHISMESSAGE = 'DELETETHISMESSAGE';
export const GETTHISCHANNELWXMESSAGE = 'GETTHISCHANNELWXMESSAGE';
export const ADDTHISCHANNELWXMESSAGE = 'ADDTHISCHANNELWXMESSAGE';



