/*
*
*Author: Fuxiaoke
*Create Time: 2018-03-13 11:24
*
*/
export const BABYINSURANCEORDERLIST = 'BABYINSURANCEORDERLIST';
export const SEARCHRESULTFORORDER = 'SEARCHRESULTFORORDER';
export const LATENTORDERLIST = 'LATENTORDERLIST';
export const CHANGEONEORDERDATA = 'CHANGEONEORDERDATA';
export const ORDERLOGLIST = 'ORDERLOGLIST';
