/**
 * Created by FuxiaoKe on 2018/3/5.
 */

export const ADDCHANNEL = 'ADDCHANNEL';
export const GETCHANNELs = 'GETCHANNELs';
export const GETWXMENU = 'GETWXMENU';
export const ADDWXMENU = 'ADDWXMENU';
export const MAKEMENU = 'MAKEMENU';
export const GETUSERS = 'GETUSERS';
export const DELETEWXMENU = 'DELETEWXMENU';
export const EDITWXMENU = 'EDITWXMENU';
export const SAVETHISMESSAGE = 'SAVETHISMESSAGE';
export const GETWXMESSAGES = 'GETWXMESSAGES';
export const CHECKOUTUSER = 'CHECKOUTUSER';
export const TOSENDMESSAGETOSOMEONE = 'TOSENDMESSAGETOSOMEONE';
export const UPLOADIMAGE = 'UPLOADIMAGE';
export const DELETETHISMESSAGE = 'DELETETHISMESSAGE';
export const GETTHISCHANNELWXMESSAGE = 'GETTHISCHANNELWXMESSAGE';
export const GETCHANNELGROUP = 'GETCHANNELGROUP';
export const ADDCHANNELGROUP = 'ADDCHANNELGROUP';
export const EDITCHANNELGROUP = 'EDITCHANNELGROUP';
export const GETTHISCHANNELGROUPLIST = 'GETTHISCHANNELGROUPLIST';
export const ALLCHANNELGROUPLIST = 'ALLCHANNELGROUPLIST';
export const ALLCHANNELLIST = 'ALLCHANNELLIST';
export const SETQRCODECOUNT = 'SETQRCODECOUNT';
