/**
 * Created by FuxiaoKe on 2018/3/5.
 */
export const ADMINUSERLISTDATA = "ADMINUSERLISTDATA";
export const ALLROLELIST = "ALLROLELIST";
export const OPERATESYSTEMUSER = "OPERATESYSTEMUSER";
export const ADMINROLELISTDATA = "ADMINROLELISTDATA";
export const DELETETHISSYSTEMUSER = "DELETETHISSYSTEMUSER";
export const OPERATESYSTEMROLE = "OPERATESYSTEMROLE";
export const DELETETHISSYSTEMROLE = "DELETETHISSYSTEMROLE";
export const SYSTEMMENULIST = "SYSTEMMENULIST";
